   const items = [  
    { text: 'Do a jigsaw puzzle', image: '../img/maze-challenge.png' },
    { text: 'Do a jigsaw puzzle', image: '#' },

                  'Find a hat in the room.',
                  'Find sunglasses in the room.',
                  'Get together and make a wave with your arms.',
                  'Guess the definition of foreign words in English. Koekje, Voetbal, Klokke. Dagbog',
                  'Walk in a circle like a crab.',
                  'Pretend you are diving.',
                  'Draw the image you see on the screen .',
                  'Make two cards stand up in a triangle.',
                  'Blow a balloon up as much as possible and tie it off.',
                  'Bounce a balloon 10 times with your feet without letting it touch the floor.',
                  'Solve the math question on the screen. 6+6x6-6 = ?',
                  'Solve the maze on the screen.',
                  'Roll a 6 with a die 3 times.',
                  'Spell out the word “TEA” with your body',
                  'Play out a scene from Titanic.',
                  'Do a small Robot dance and name the move.',
                  'Balance an object on your head and walk across the room.',
                  'Name 3 things that rhyme with duck.',
                  'Find the word in the scrambled letters. The first and last letters are correct! MREAROOTHBD, CPEMOTUR, MTONOIR',
                  'Make a paper airplane and fly it.', 
                  'Write your name with your non-dominant hand.', 
                  'Say “How much wood would a woodchuck chuck if a woodchuck could chuck wood” 3 times.', 
                  'Find 3 things that start with the letter "B" in the room.', 
                  'Play Rock paper scissors until one person has won 3 times.', 
                  'Do 5 sit-ups.', 
                  'What has keys but can not open locks?', 
                  'Pop the balloon in a funny way.', 
                  'Name two songs that have the word love in it. (sing a bit)', 
                  'Spin 10 times then do a high five.'
                ];