   const items = [  
    { text: 'Find a hat in the room.', image: '' },
    { text: 'Find sunglasses in the room.', image: '' },
    { text: 'Get together and make a wave with your arms.', image: '' },
    { text: 'Guess the definition of foreign words in English. Koekje, Voetbal, Klokke. Dagbog', image: '' },
    { text: 'Walk in a circle like a crab.', image: '' },
    { text: 'Pretend you are diving.', image: '' },
    { text: 'Draw the image you see on the screen .', image: '../img/pen-robot.png' },
    { text: 'Make two cards stand up in a triangle.', image: '' },
    { text: 'Blow up a balloon as much as possible and tie it off.', image: '' },
    { text: 'Bounce a balloon 10 times with your feet without letting it touch the floor.', image: '' },
    { text: 'Solve the math question on the screen. 6+6x6-6 = ?', image: '../img/math.png' },
    { text: 'Solve the maze on the screen.', image: '../img/maze-challenge.png' },
    { text: 'Roll a 6 with a die 3 times.', image: '' },
    { text: 'Spell out the word “TEA” with your body', image: '' },
    { text: 'Play out a scene from Titanic.', image: '' },
    { text: 'Do a Robot dance and name the move.', image: '' },
    { text: 'Balance an object on your head and walk across the room.', image: '' },
    { text: 'Name 3 things that rhyme with duck.', image: '' },
    { text: 'Find the word in the scrambled letters. The first and last letters are correct! MREAROOTHBD, CPEMOTUR, MTONOIR', image: '#' },
    { text: 'Make a paper airplane and fly it.', image: '' },
    { text: 'Write all players name with your non-dominant hand.', image: '' },
    { text: 'Say “How much wood would a woodchuck chuck if a woodchuck could chuck wood” 3 times.', image: '' },
    { text: 'Find 3 things that start with the letter "B" in the room.', image: '' },
    { text: 'lay Rock paper scissors until one person has won 3 times.', image: '' },
    { text: 'Do 5 sit-ups.', image: '' },
    { text: 'Awnser the riddle: What has keys but can not open locks?', image: '' },
    { text: 'Pop the balloon in a funny way.', image: '' },
    { text: 'Name two songs that have the word love in it. (sing a bit)', image: '' },
    { text: 'Spin 10 times then do a high five.', image: '' }
                ];